### ISSUE TITLE
describeTable is not a function

### ISSUE THREAD

**Issue by vigalo** [rkotcherr/multi-tenant-migrate#2]
Hello, rkotcherr : 

Great job with this repo!. 
My migrations are working great, for public and tenant schemas. I only have a problem trying to use queryInterface.describeTable to check if one field I'm trying to add doesn't exist yet.
It trows this error : 
```
Error from child migration: queryInterface.describeTable is not a function
```
A console.log of the queryInterface object : 
```
queryInterface { addColumn: [Function: addColumn],
  addConstraint: [Function: addConstraint],
  addIndex: [Function: addIndex],
  bulkDelete: [Function: bulkDelete],
  bulkInsert: [Function: bulkInsert],
  changeColumn: [Function: changeColumn],
  createFunction: [Function: createFunction],
  createTable: [Function: createTable],
  dropFunction: [Function: dropFunction],
  dropTable: [Function: dropTable],
  removeColumn: [Function: removeColumn],
  removeConstraint: [Function: removeConstraint],
  removeIndex: [Function: removeIndex],
  renameColumn: [Function: renameColumn],
  renameFunction: [Function: renameFunction],
  renameTable: [Function: renameTable],
  upsert: [Function: upsert] }
```
Can you help me?
Thanks

**Comment by vigalo** [comment]
Taking a look to the source code, I have seen there is a wrapper in the worker to the queryInterface object and the describeTable was not implemented. I added the implementation and now is working.

Thanks

**Comment by nguyenphuocnhatthanh** [comment]
@vigalo  could you make the PR? I got the same issue.
